---
# tasks file for ansible_traefik - provisioning

- name: Create folder for stack files
  file: 
    path: "{{ traefik_stack_path }}"
    state: directory
    recurse: yes
    owner: "root"
    group: "root"
